# Generated by Django 2.0 on 2019-07-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50, verbose_name='职位')),
                ('company', models.CharField(max_length=100, verbose_name='公司')),
                ('date', models.CharField(max_length=100, verbose_name='发布时间')),
                ('location', models.CharField(max_length=20, verbose_name='地点')),
                ('da_value', models.CharField(max_length=100, verbose_name='时间返回值')),
                ('di_value', models.CharField(max_length=100, verbose_name='地点类型返回值')),
                ('cp_value', models.CharField(max_length=100, verbose_name='职位类型返回值')),
            ],
        ),
        migrations.CreateModel(
            name='UrlModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256)),
            ],
        ),
    ]
