# Generated by Django 2.0 on 2019-06-21 03:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('1[34578]\\d{9}', message='请输入正确格式的手机号码！')]),
        ),
    ]
