# Generated by Django 2.0 on 2019-06-25 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import front.models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
            options={
                'permissions': [('view_article', '看文章的权限')],
            },
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', front.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
